- name: "Checking Ansible config for {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yaml"
  register: "distribution_config"
  tags: always
