# this is the starting point of the ansible script
# divide the roles into different tags for easier management of different environments
- name: Setup Personal Environment
  hosts: this_pc
  connection: local
  roles:
    - alacritty
    - applications
    - bat
    - fastfetch
    - git
    - hyprland
    - keyd
    - lazygit
    - mako
    - neovim
    - nodejs
    - rofi
    - scripts
    - starship
    - tmux
    - wallpapers
    - yazi
    - zathura
    - zellij
    - zsh
  tags:
    - always
