- name: "Setup Config for {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - common_tasks/setup_config_dir_linux.yaml
  when: (configure | default(true)) | bool  # Default to true if not defined
  tags:
    - xfce4
