- name: "Install on {{ ansible_distribution }}"
  become: true
  ansible.builtin.pacman:
    name:
      - "{{ role_name }}"
    state: latest

- name: "Setup Config for {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - common_tasks/setup_config_dir_linux.yaml
    - common_tasks/setup_data_dir_linux.yaml
  vars:
    role_config_directory_suffix: "nvim/"
    role_data_directory_suffix: "nvim/"
