- name: "Checking Ansible config for {{ ansible_distribution }}"
  ansible.builtin.import_tasks: common_tasks/ansible_distribution_check.yaml
  tags:
    - neovim
    - cli

- name: "Run Tasks for {{ ansible_distribution }}"
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution | lower }}.yaml"
    apply:
      tags:
        - neovim
        - cli
  when: distribution_config.stat.exists
  tags:
    - neovim
    - cli
